ansi2html from pip, markup

diff --git a/.github/workflows/review.yml b/.github/workflows/review.yml
--- a/.github/workflows/review.yml
+++ b/.github/workflows/review.yml
@@ -55,10 +55,6 @@ jobs:
           path: tmp
           key: cred-data-${{ hashFiles('snapshot.json') }}
 
-      - name: install ansi2html
-        if: steps.cache-data.outputs.cache-hit != 'true'
-        run: sudo apt update && sudo apt install colorized-logs
-
       - name: Set up Python 3.10
         if: steps.cache-data.outputs.cache-hit != 'true'
         uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0 - 2025.01.28
@@ -100,7 +96,7 @@ jobs:
 
   # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
 
-  review_base:
+  review_base_and_diff:
 
     needs: [ download_repos ]
 
@@ -144,10 +140,6 @@ jobs:
           path: tmp
           key: cred-data-${{ hashFiles('snapshot.json') }}
 
-      - name: install ansi2html
-        if: steps.cache-data.outputs.cache-hit != 'true'
-        run: sudo apt update && sudo apt install colorized-logs
-
       - name: Set up Python 3.10
         if: steps.cache-data.outputs.cache-hit != 'true'
         uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0 - 2025.01.28
@@ -163,6 +155,18 @@ jobs:
           python review_data.py &>review_base.txt
           ansi2html --style 'pre {font-family: monospace; font-size: large}' <review_base.txt  >review_base.html
 
+      - name: Download all workflow run artifacts
+        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8 - 2024.07.05
+
+      - name: Get diff for review
+        run: |
+          # in case of difference - diff returns failure
+          if ! diff --unified=1 --color=auto review_base.txt review_head/review_head.txt &>review_diff.txt; then
+            cat review_diff.txt | ansi2html --style 'pre {font-family: monospace; font-size: large}' >review_diff.html
+          else
+            touch review_diff.html
+          fi
+
       - name: Upload artifact
         if: always()
         uses: actions/upload-artifact@65c4c4a1ddee5b72f698fdd19549f0f0fb45cf08 # v4.6.0 - 2025.01.09
@@ -171,36 +175,6 @@ jobs:
           path: |
             review_base.txt
             review_base.html
-
-  # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
-
-  diff_review:
-
-    needs: [ download_repos, review_base ]
-
-    runs-on: ubuntu-latest
-
-    steps:
-
-      - name: Harden Runner
-        uses: step-security/harden-runner@cb605e52c26070c328afc4562f0b4ada7618a84e # v2.10.4 - 2025.01.20
-        with:
-          egress-policy: audit
-
-      - name: install ansi2html
-        run: sudo apt update && sudo apt install colorized-logs
-
-      - name: Download all workflow run artifacts
-        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4.1.8 - 2024.07.05
-
-      - name: Get diff for review
-        run: |
-          # in case of difference - diff returns failure
-          if ! diff --unified=1 --color=auto review_base/review_base.txt review_head/review_head.txt &>review_diff.txt; then
-            cat review_diff.txt | ansi2html --style 'pre {font-family: monospace; font-size: large}' >review_diff.html
-          else
-            touch review_diff.html
-          fi
 
       - name: Upload artifact
         if: always()
